import React from 'react'
import { Metadata } from 'next';

    
export const metadata: Metadata = {
  title: "About Us | Nepali Pasal",
  description: "Generated by create next app",
};

const AboutPage = () => {

  return (
    <main>

        <div>About us Page</div>
    </main>
  )
}

export default AboutPage