import React from 'react'
import { Metadata } from 'next';

   
export const metadata: Metadata = {
  title: "Contact Us | Nepali Pasal",
  description: "Generated by create next app",
  keywords: ['products',  'product',]
};

const ContactPage = () => {
 
  return (
    <main>

        <div>Contact us Page</div>
    </main>
  )
}

export default ContactPage